# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'WhereIsMyStuff' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WhereIsMyStuff
   pod 'Mapbox-iOS-SDK', '~> 5.9'
   pod 'MapboxGeocoder.swift', '~> 0.11'

  target 'WhereIsMyStuffTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WhereIsMyStuffUITests' do
    # Pods for testing
  end

end
